### ISSUE TITLE
No Error Checking is Implemented

### ISSUE THREAD

**Issue by PercentBoat4164** [betapictoris/modrinth.py#5]
**Bug Description**
A `KeyError` is thrown by the first `__get_item__()` call to `rJSON` after any request to the Modrinth API is made. This is due to the lack of error checking. When an error (i.e. a `ratelimit_error`) is present, the keys requested from the dictionary do not exist.

**To Reproduce**
1. Make more than 300 requests in a single minute.
2. Be ratelimited.
3. Observe badness.

**Expected Behavior**
Throw an exception.

**Comment by betapictoris** [comment]
Closing because I'm starting clean for a 1.0 release.
