### ISSUE TITLE
Get latest version for the given Minecraft Version

### ISSUE THREAD

**Issue by v-pun215** [BetaPictoris/modrinth.py#8]
So, I am making a Mod Manager in Python, using this API. One of the most important features of any Mod Manager is to *download* mods. Basically, what I want is that the user enters the ID or Slug of a mod (from Modrinth of course) then the user inputs the wanted Minecraft Version of the mod. Then it automatically downloads it. Directory management is not needed, as I already have a module for that. I'm sorry if this is already implemented. The docs really aren't that clear.

Peace out,
v-pun215

**Comment by BetaPictoris** [comment]
This is on the [to-do](https://github.com/BetaPictoris/modrinth.py#to-do) list, I'll look at this today and try to get something to work.

**Comment by BetaPictoris** [comment]
Done! Good luck with your project!
